---
- name: Remove Existing Timezone File
  become: yes
  file:
      path: /etc/localtime
      state: absent
  when: time_install

- name: Link Specified Timezone File
  become: yes
  file:
      src: "/usr/share/zoneinfo/{{ time_timezone }}"
      path: "/etc/localtime"
      state: link
  when: time_install

- name: Test Timezone Changes
  command: "date"
  when: time_install
