---
- name: Set Timezone
  become: yes
  command: "timedatectl set-timezone {{ time_timezone }}"
  when: time_install and (ansible_distribution == "RedHat")

- name: Test Timezone Changes
  command: "timedatectl"
  when: time_install and (ansible_distribution == "RedHat")
